import { Member } from './member';

export const MEMBERS: Member[] = [
  {id: 1, name: 'Ken Weaver', skills: []},
  {id: 2, name: 'Mitch Chanin', skills: []},
  {id: 3, name: 'Florence', skills: []},
  {id: 4, name: 'Dave Loeb', skills: []},
  {id: 5, name: 'Jean', skills: []},
  {id: 6, name: 'Ann', skills: []},
  {id: 7, name: 'Meenal', skills: []},
  {id: 8, name: 'Aditya', skills: []},
  {id: 9, name: 'Pat Libbey', skills: []},
  {id: 10, name: 'Lou Ann', skills: []},
  {id: 11, name: 'Judy Morgan', skills: []},
  {id: 12, name: 'Michael Schreiber', skills: []},
  {id: 13, name: 'Dave and Marion', skills: []},
  {id: 14, name: 'Tam Clements', skills: []},
  {id: 15, name: 'Miriam', skills: []},
  {id: 16, name: 'Chuck Best', skills: []},
  {id: 17, name: 'Nadine Young', skills: []},
  {id: 18, name: 'Lindsey', skills: []},
  {id: 19, name: 'Tim Siftar', skills: []},
  {id: 20, name: 'Alicia Dorsey', skills: []},
  {id: 21, name: 'Sam Mastriano', skills: []},
  {id: 22, name: 'Matt Wang', skills: []},
  {id: 23, name: 'Sarah Davidson', skills: []},
  {id: 24, name: 'Rhonda', skills: []},
  {id: 25, name: 'Karen Melton', skills: []},
  {id: 26, name: 'Peter Winslow', skills: []},
  {id: 27, name: 'Eugene', skills: []},
  {id: 28, name: 'Katie Blumberh', skills: []},
]